[package]
name = "lab2"
version = "0.1.0"
authors = ["johnny-keker <isarzhevsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"